### ISSUE TITLE
Use Underscore Template to Remove HTML from JS

### ISSUE THREAD

**Issue by spaceninja** [spaceninja/date-list#6]
From @vosechu:

> Okay, this is by far my favorite part of underscore. I hate seeing html in my scripts (even though I hear that's a thing now), so I like using underscore templates + jquery finders to stash templates in the page and act on them.

> Something like this:

```
var template = _.template($("#rowTemplate"))
$("table").append(template(date.event, eventDate.calendar(...), durationText))
```

http://underscorejs.org/#template
http://stackoverflow.com/questions/4912586/explanation-of-script-type-text-template-script

**Comment by spaceninja** [comment]
Another option: https://benfrain.com/html-templating-with-vanilla-javascript-es2015-template-literals/

**Comment by vosechu** [comment]
I don’t understand the desire to put html in the js instead of doing a
script tag template in the html that you can hydrate later?

But it’s cool that this is now mostly in es2015 though. I say mostly
because you still need something like the lit-html library to not suffer
xss attacks (or call the textContent function on all data? Wasn’t sure if
that was the idea)

Anyways, super neat! Thank you for showing!

**Comment by spaceninja** [comment]
No longer relevant (rebuilt in Vue)
